### ISSUE TITLE
llama-box crashes when running the bge-m3 embedding model in some cases

### ISSUE THREAD

**Issue by Finenyaco** [gpustack/gpustack#147]
**Is your enhancement related to a problem? Please describe.**

1. Deploy a bge-m3 model (vonjack/bge-m3-gguf/bge-m3-f16.gguf)
2. Integrate with Dify to create a knowledge base.  If the context size is set to 2048, llama-box is prone to crashes
<img width="626" alt="image" src="https://github.com/user-attachments/assets/5e5333cd-3805-44ae-9e2b-c3a6bd377737">

<img width="1555" alt="image" src="https://github.com/user-attachments/assets/9556b336-865c-41a7-abe3-f177acc71f20">

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by thxCode** [comment]
https://github.com/gpustack/llama-box/issues/13

**Comment by thxCode** [comment]
fixed in llama-box v0.0.98

**Comment by Finenyaco** [comment]
Model under test: Hugging Face/vonjack/bge-m3-gguf

- llama-box v0.0.98: It still crashes
```
0.26.561.023 I slt              update_slots: rid 23016778138 | id 01 | task 12 | new prompt, n_ctx_slot = 8, n_keep = 0, n_prompt_tokens = 1
0.26.561.024 D slt              update_slots: rid 23016778138 | id 01 | task 12 | kv cache rm [0, end)
0.26.561.024 I slt              update_slots: rid 23016778138 | id 01 | task 12 | prompt processing, n_past = 1, n_tokens = 1, n_prompt_tokens = 1, n_preprocessed_tokens = 0
0.26.561.026 I slt              update_slots: rid 23016778138 | id 01 | task 12 | prompt done, n_past = 1, n_tokens = 1
0.26.561.026 D srv              update_slots: decoding batch, n_tokens = 1
/home/runner/work/llama-box/llama-box/llama.cpp/src/llama.cpp:18249: GGML_ASSERT(seq_id < n_tokens && "seq_id cannot be larger than n_tokens with pooling_type == CLS or RANK") failed
gdb: warning: Couldn't determine a path for the index cache directory.
[New LWP 37424]
[New LWP 37425]
[New LWP 37426]
[New LWP 37427]
[New LWP 37428]
[New LWP 37429]
[New LWP 37430]
[New LWP 37431]
[New LWP 37432]
[New LWP 37433]
[New LWP 37434]
[New LWP 37435]
[New LWP 37436]
[New LWP 37437]
[New LWP 37438]
[New LWP 37439]
[New LWP 37440]
[New LWP 37441]
[New LWP 37442]
[New LWP 37443]
[New LWP 37444]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
0x000073cb548ea42f in __GI___wait4 (pid=37542, stat_loc=0x7fff21e1cb04, options=0, usage=0x0) at ../sysdeps/unix/sysv/linux/wait4.c:30
30	../sysdeps/unix/sysv/linux/wait4.c: No such file or directory.
#0  0x000073cb548ea42f in __GI___wait4 (pid=37542, stat_loc=0x7fff21e1cb04, options=0, usage=0x0) at ../sysdeps/unix/sysv/linux/wait4.c:30
30	in ../sysdeps/unix/sysv/linux/wait4.c
#1  0x00000000009f1b1a in ggml_abort ()
#2  0x00000000006d9ec3 in llama_set_inputs(llama_context&, llama_ubatch const&) ()
#3  0x0000000000721ff5 in llama_decode_internal(llama_context&, llama_batch) ()
#4  0x0000000000723067 in llama_decode ()
#5  0x000000000052aa32 in server_context::update_slots() ()
#6  0x000000000053543a in server_task_queue::start_loop() ()
#7  0x0000000000438427 in main ()
[Inferior 1 (process 37423) detached]
```

- llama-box v0.0.103

Issue 1: There was no response under the same test case

logs of llama-box:
```
1.04.870.991 I srv        log_server_request: rid 23410993094 | POST /v1/embeddings 127.0.0.1:48696
1.04.871.004 I srv oaicompat_embeddings_requ: rdi 23410993094 | {"encoding_format":"base64","input":[""]}
1.04.871.009 D srv    create_tasks_inference: creating multi-prompt tasks, n_prompts = 1
1.04.871.012 D srv              submit_tasks: add task 4 to waiting list. current waiting = 0 (before add)
1.04.871.012 D que              submit_tasks: new task, id = 4/1, front = 0
1.04.871.056 D que                start_loop: processing new tasks
1.04.871.060 D que                start_loop: processing task, id = 4
1.04.871.061 D slt        get_available_slot: id 01 | task -1 | selected slot by lru, t_last = -1
1.04.871.061 D srv       process_single_task: no slot is unsatisfied, defer task, id_task = 4
1.04.871.062 D que                     defer: defer task, id = 4
1.04.871.063 D que                start_loop: update slots
1.04.871.063 D srv              update_slots: all slots are idle
1.04.871.063 D que                start_loop: waiting for new tasks
```

Issue 2: Using certain Chinese characters, such as `，` and `：`, causes errors

```
8.10.949.814 I srv        log_server_request: rid 23837071916 | POST /v1/embeddings 192.168.50.174:43756
8.10.949.834 I srv oaicompat_embeddings_requ: rdi 23837071916 | {"encoding_format":"float","input":["你好，","test"],"model":"bge-m3-fp16"}
8.10.949.886 E srv      log_server_exception: rid 23837071916 | exception = _Map_base::at
8.10.949.925 I srv       log_server_response: rid 23837071916 | POST /v1/embeddings 192.168.50.174:43756 | status 500 | cost 0.00s
```

**Comment by Finenyaco** [comment]
Verified in main 7602b46, llama-box v0.0.104
